### ISSUE TITLE
error with making a volume

### ISSUE THREAD

**Issue by rykuehn** [dylanlrrb/Please-Contain-Yourself#12]
For development purposes, NPM install should be installed on local machine?
Nodemon does not exist.

**Comment by dylanlrrb** [comment]
For modules 4 and 5, I included the dependencies in the module. This should fix the problem where mounted volumes hide the dependencies already in the container. This only happens when the user doesn't install the node_modules (which they really shouldn't have to) when mounting a volume. This is so users without node or npm installed on their computer can complete the module without doing so. Module 6 will go into a method of containerizing a project's dependencies so this problem can be avoided.
Thanks again for the catch!
